import { ArmourSubCategoryMap } from "../../../global-types";

export const armourData: ArmourSubCategoryMap = {
  "Commonfolk&Wanderers": [
    {
      type: "armour",
      pieceType: "set",
      name: "Guilty",
      collected: false,
      link: "Link",
      dlc: false,
      items: [
        {
          type: "armour",
          pieceType: "helm",
          name: "Guilty’s Helm",
          collected: false,
          link: "Link",
          dlc: false,
          children: [
            {
              type: "armour",
              pieceType: "helm",
              name: "Guilty’s Helm (altered)",
              collected: false,
              dlc: false,
              link: "link",
            },
          ],
        },
        {
          type: "armour",
          pieceType: "gloves",
          name: "Traveler’s Gloves",
          collected: false,
          link: "Link",
          dlc: false,
        },
        {
          type: "armour",
          pieceType: "chest",
          name: "Traveler’s Chest",
          collected: false,
          link: "Link",
          dlc: false,
          children: [
            {
              type: "armour",
              pieceType: "chest",
              name: "Guilty’s chest (altered)",
              collected: false,
              dlc: false,
              link: "link",
            },
          ],
        },
        {
          type: "armour",
          pieceType: "boots",
          name: "Guilty’s Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      ],
    },
    /*   {
      type: "armour",
      name: "Traveler’s",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Traveler’s Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: null,
        gloves: {
          type: "armour",
          name: "Traveler’s Gloves",
          collected: false,
          link: "Link",
          dlc: false,
        },
        boots: {
          type: "armour",
          name: "Traveler’s Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Commoner’s",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Commoner’s Helm",
          collected: false,
          link: "Link",
          dlc: false,
          alteredVersion: {
            name: "Commoner’s Helm (Altered)",
            collected: false,
            link: "Link",
          },
        },
        chest: {
          type: "armour",
          name: "Commoner’s Chest",
          collected: false,
          link: "Link",
          dlc: false,
          alteredVersion: {
            name: "Commoner’s Chest (Altered)",
            collected: false,
            link: "Link",
          },
        },
        gloves: null,
        boots: null,
      },
    },
    {
      type: "armour",
      name: "Aristocrat",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Aristocrat Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: {
          type: "armour",
          name: "Aristocrat Chest",
          collected: false,
          link: "Link",
          dlc: false,
        },
        gloves: {
          type: "armour",
          name: "Aristocrat Gloves",
          collected: false,
          link: "Link",
          dlc: false,
        },
        boots: {
          type: "armour",
          name: "Aristocrat Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Soldier Noble",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Soldier Noble Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: {
          type: "armour",
          name: "Soldier Noble Chest",
          collected: false,
          link: "Link",
          dlc: false,
        },
        gloves: null,
        boots: {
          type: "armour",
          name: "Soldier Noble Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Old Aristocrat",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Old Aristocrat Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: {
          type: "armour",
          name: "Old Aristocrat Chest",
          collected: false,
          link: "Link",
          dlc: false,
        },
        gloves: null,
        boots: {
          type: "armour",
          name: "Old Aristocrat Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Page",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Page Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: {
          type: "armour",
          name: "Page Chest",
          collected: false,
          link: "Link",
          dlc: false,
        },
        gloves: null,
        boots: {
          type: "armour",
          name: "Page Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "High Page",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "High Page Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: {
          type: "armour",
          name: "High Page Chest",
          collected: false,
          link: "Link",
          dlc: false,
        },
        gloves: null,
        boots: {
          type: "armour",
          name: "High Page Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Guardian",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Guardian Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: {
          type: "armour",
          name: "Guardian Chest",
          collected: false,
          link: "Link",
          dlc: false,
        },
        gloves: {
          type: "armour",
          name: "Guardian Gloves",
          collected: false,
          link: "Link",
          dlc: false,
        },
        boots: {
          type: "armour",
          name: "Guardian Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Festive",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Festive Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: null,
        gloves: null,
        boots: {
          type: "armour",
          name: "Festive Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Blue Festive",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Blue Festive Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: null,
        gloves: null,
        boots: {
          type: "armour",
          name: "Blue Festive Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Prisoner",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Prisoner Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: null,
        gloves: {
          type: "armour",
          name: "Prisoner Gloves",
          collected: false,
          link: "Link",
          dlc: false,
        },
        boots: null,
      },
    },
    {
      type: "armour",
      name: "Hornsent",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: null,
        chest: null,
        gloves: null,
        boots: {
          type: "armour",
          name: "Hornsent Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Bloodsoaked",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: null,
        chest: {
          type: "armour",
          name: "Bloodsoaked Chest",
          collected: false,
          link: "Link",
          dlc: false,
        },
        gloves: {
          type: "armour",
          name: "Bloodsoaked Gloves",
          collected: false,
          link: "Link",
          dlc: false,
        },
        boots: {
          type: "armour",
          name: "Bloodsoaked Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    },
    {
      type: "armour",
      name: "Mushroom",
      collected: false,
      link: "Link",
      dlc: false,
      children: {
        helm: {
          type: "armour",
          name: "Mushroom Helm",
          collected: false,
          link: "Link",
          dlc: false,
        },
        chest: {
          type: "armour",
          name: "Mushroom Chest",
          collected: false,
          link: "Link",
          dlc: false,
        },
        gloves: null,
        boots: {
          type: "armour",
          name: "Mushroom Boots",
          collected: false,
          link: "Link",
          dlc: false,
        },
      },
    }, */
  ],
  "Scholars&Seers": [],
  "Cultists&Nobles": [],
  "Rogues&Outcasts": [],
  "Militia&FringeWarriors": [],
  RankedSoldiers: [],
  "EliteKnights&Legends": [],
  KnightlyOrders: [],
  NamedChampions: [],
  "Warlords & Colossi": [],
  pieces: [],
};
