import { TalismansSubCategoryMap } from "../../../global-types";

export const talismansData: TalismansSubCategoryMap = {
  category1: [
    {
      type: "talismans",
      name: "Crimson Amber Medallion",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimson+Amber+Medallion",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
        { tier: 3, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Crimson Seed Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimson+Seed+Talisman",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Blessed Dew Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blessed+Dew+Talisman",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Cerulean Amber Medallion",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cerulean+Amber+Medallion",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
        { tier: 3, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Cerulean Seed Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cerulean+Seed+Talisman",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Blessed Blue Dew Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blessed+Blue+Dew+Talisman",
      dlc: true,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Talisman of Lord's Bestowal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Talisman+of+Lord's+Bestowal",
      dlc: true,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Viridian Amber Medallion",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Viridian+Amber+Medallion",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
        { tier: 3, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Green Turtle Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Green+Turtle+Talisman",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Two-Headed Turtle Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Two-Headed+Turtle+Talisman",
      dlc: true,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Arsenal Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Arsenal+Charm",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
      ],
    },
    {
      type: "talismans",
      name: "Great-Jar's Arsenal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great-Jar's+Arsenal",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Erdtree's Favor",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Erdtree's+Favor",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false, legendary: true },
      ],
    },
    {
      type: "talismans",
      name: "Radagon's Scarseal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Radagon's+Scarseal",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Radagon's Soreseal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Radagon's+Soreseal",
      dlc: false,
      legendary: true,
    },
    {
      type: "talismans",
      name: "Marika's Soreseal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Marika's+Soreseal",
      dlc: false,
      legendary: true,
    },
    {
      type: "talismans",
      name: "Marika's Scarseal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Marika's+Scarseal",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Starscourge Heirloom",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Starscourge+Heirloom",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Prosthesis-Wearer Heirloom",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Prosthesis-Wearer+Heirloom",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Stargazer Heirloom",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stargazer+Heirloom",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Two Fingers Heirloom",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Two+Fingers+Heirloom",
      dlc: false,
      legendary: false,
    },
    {
      type: "talismans",
      name: "Outer God Heirloom",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Outer+God+Heirloom",
      dlc: true,
      legendary: false,
    },
  ],
  category2: [
    {
      type: "talismans",
      name: "Dragoncrest Shield Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragoncrest+Shield+Talisman",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
      ],
    },
    {
      type: "talismans",
      name: "Dragoncrest Greatshield Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragoncrest+Greatshield+Talisman",
      dlc: false,
      legendary: true,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Spelldrake Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spelldrake+Talisman",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
        { tier: 3, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Flamedrake Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flamedrake+Talisman",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
        { tier: 3, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Boltdrake Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Boltdrake+Talisman",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
        { tier: 3, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Haligdrake Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Haligdrake+Talisman",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
      ],
    },
    {
      type: "talismans",
      name: "Golden Braid",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Braid",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Pearldrake Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Pearldrake+Talisman",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false },
        { tier: 3, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Immunizing Horn Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Immunizing+Horn+Charm",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Stalwart Horn Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stalwart+Horn+Charm",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Clarifying Horn Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Clarifying+Horn+Charm",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Mottled Necklace",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Mottled+Necklace",
      dlc: false,
      legendary: false,
      versions: [
        { tier: 0, collected: false },
        { tier: 1, collected: false },
        { tier: 2, collected: false, dlc: true },
      ],
    },
    {
      type: "talismans",
      name: "Prince of Death's Pustule",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Prince+of+Death%27s+Pustule",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Prince of Death's Cyst",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Prince+of+Death%27s+Cyst",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Ailment Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ailment+Talisman",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
  ],
  category3: [
    {
      type: "talismans",
      name: "Dagger Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dagger+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Curved Sword Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Curved+Sword+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Twinblade Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Twinblade+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Axe Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Axe+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Hammer Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hammer+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Spear Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spear+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Lance Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lance+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Claw Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Claw+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Two-Handed Sword Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Two-Handed+Sword+Talisman",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Greatshield Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greatshield+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Pearl Shield Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Pearl+Shield+Talisman",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Retaliatory Crossed-Tree",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Retaliatory+Crossed-Tree",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/retaliatory_crossed-tree_1_talisman_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png",
    },
    {
      type: "talismans",
      name: "Lacerating Crossed-Tree",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lacerating+Crossed-Tree",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/lacerating_crossed-tree_1_talisman_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png",
    },
    {
      type: "talismans",
      name: "Arrow's Sting Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Arrow%27s+Sting+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Arrow's Reach Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Arrow%27s+Reach+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Arrow's Soaring Sting Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Arrow%27s+Soaring+Sting+Talisman",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Sharpshot Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sharpshot+Talisman",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
  ],
  category4: [
    {
      type: "talismans",
      name: "Graven-School Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Graven-School+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Graven-Mass Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Graven-Mass+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Fathful Canvas Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fathful+Canvas+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Flock's Canvas Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flock%27s+Canvas+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Primal Glinstone Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Primal+Glinstone+Blade",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Moon of Nokstella",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Moon+of+Nokstella",
      dlc: false,
      legendary: true,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Old Lord's Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Old+Lord%27s+Talisman",
      dlc: false,
      legendary: true,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Radagon Icon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Radagon+Icon",
      dlc: false,
      legendary: true,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Beloved Stardust",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Beloved+Stardust",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
  ],
  category5: [
    {
      type: "talismans",
      name: "Roar Medallion",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Roar+Medallion",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Companion Jar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Companion+Jar",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Perfumer's Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Perfumer%27s+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Carian Filigreed Crest",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Carian+Filigreed+Crest",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Warrior Jar Shard",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Warrior+Jar+Shard",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Shard of Alexander",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shard+of+Alexander",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Godfrey Icon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Godfrey+Icon",
      dlc: false,
      legendary: true,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Rellana's Cameo",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rellana%27s+Cameo",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Shattered Stone Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shattered+Stone+Talisman",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Smithing Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Talisman",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Enraged Divine Beast",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Enraged+Divine+Beast",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Talisman of the Dread",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Talisman+of+the+Dread",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
  ],
  category6: [
    {
      type: "talismans",
      name: "Bull-Goat's Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bull-Goat%27s+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Blue Dancer Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blue+Dancer+Charm",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Verdigris Discus",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Verdigris+Discus",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Fire Scorpion Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fire+Scorpion+Charm",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Lightning Scorpion Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lightning+Scorpion+Charm",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Magic Scorpion Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Magic+Scorpion+Charm",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Sacred Scorpion Charm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sacred+Scorpion+Charm",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Crucible Scale Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crucible+Scale+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Crucible Feather Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crucible+Feather+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Crucible Knot Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crucible+Knot+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Fine Crucible Feather Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fine+Crucible+Feather+Talisman",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Talisman of all Crucibles",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Talisman+of+all+Crucibles",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
  ],
  category7: [
    {
      type: "talismans",
      name: "Red-Feathered Branchsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Red-Feathered+Branchsword",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Blue-Feathered Branchsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blue-Feathered+Branchsword",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Ritual Sword Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ritual+Sword+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Ritual Shield Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ritual+Shield+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Assassin's Crimson Dagger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Assassin%27s+Crimson+Dagger",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Assassin's Cerulean Dagger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Assassin%27s+Cerulean+Dagger",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Winged Sword Insignia",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Winged+Sword+Insignia",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Rotten Winged Sword Insignia",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rotten+Winged+Sword+Insignia",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Millicent's Prosthesis",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Millicent%27s+Prosthesis",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Godskin Swadlling Cloth",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Godskin+Swadlling+Cloth",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Kindred of Rot's Exultation",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Kindred+of+Rot%27s+Exultation",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Lord of Blood's Exultation",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lord+of+Blood%27s+Exultation",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Aged One's Exultation",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Aged+One%27s+Exultation",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "St Trina's Smile",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/St.+Trina's+Smile",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/st._trinas_smile_talisman_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png",
    },
    {
      type: "talismans",
      name: "Blade of Mercy",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blade+of+Mercy",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Taker's Cameo",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Taker%27s+Cameo",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Ancestral Spirit's Horn",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ancestral+Spirit%27s+Horn",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Crusade Insignia",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crusade+Insignia",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Dried Bouquet",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dried+Bouquet",
      dlc: true,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Gold Scarab",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gold+Scarab",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Silver Scarab",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Silver+Scarab",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
  ],
  category8: [
    {
      type: "talismans",
      name: "Crepus's Vial",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crepus%27s+Vial",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Concealing Veil",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Concealing+Veil",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Longtail Cat Talisman",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Longtail+Cat+Talisman",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Furled Finger's Trick-Mirror",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Furled+Finger%27s+Trick-Mirror",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Host's Trick-Mirror",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Host%27s+Trick-Mirror",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Shabriri's Woe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shabriri%27s+Woe",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Daedicar's Woe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Daedicar%27s+Woe",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
    {
      type: "talismans",
      name: "Sacrificial Twig",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sacrificial+Twig",
      dlc: false,
      legendary: false,
      versions: [{ tier: 0, collected: false }],
    },
  ],
};
