import type { GesturesSubCategoryMap } from "../../../global-types";

export const gesturesData: GesturesSubCategoryMap = {
  gestures: [
    {
      type: "gestures",
      name: "Point Forwards",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Point_Forwards",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Point Upwards",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Point_Upwards",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Point Downwards",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Point_Downwards",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Wait!",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wait!",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Calm Down!",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Calm_Down!",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Wave",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wave",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Beckon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Beckon",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Casual Greeting",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Casual_Greeting",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Warm Welcome",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Warm_Welcome",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Bravo!",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bravo!",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Strength!",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Strength!",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Jump for Joy",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Jump_for_Joy",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Triumphant Delight",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Triumphant_Delight",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Fancy Spin",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fancy_Spin",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Nod in Thought",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Nod_in_Thought",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Finger Snap",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Finger_Snap",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Rallying Cry",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rallying_Cry",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Heartening Cry",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Heartening_Cry",
      dlc: false,
    },
    {
      type: "gestures",
      name: "May the Best Win",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/May_the_Best_Win",
      dlc: true,
    },
    {
      type: "gestures",
      name: "Bow",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bow",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Polite Bow",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Polite_Bow",
      dlc: false,
    },
    {
      type: "gestures",
      name: "As You Wish",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/As_You_Wish",
      dlc: false,
    },
    {
      type: "gestures",
      name: "My Thanks",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/My_Thanks",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Curtsy",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Curtsy",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Reverential Bow",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Reverential_Bow",
      dlc: false,
    },
    {
      type: "gestures",
      name: "My Lord",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/My_Lord",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Let Us Go Together",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Let_Us_Go_Together",
      dlc: true,
    },
    {
      type: "gestures",
      name: "O Mother",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/O_Mother",
      dlc: true,
    },
    {
      type: "gestures",
      name: "What Do You Want?",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/What_Do_You_Want?",
      dlc: false,
    },
    {
      type: "gestures",
      name: "By My Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/By_My_Sword",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Hoslow's Oath",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hoslow's_Oath",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Fire Spur Me",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fire_Spur_Me",
      dlc: false,
    },
    {
      type: "gestures",
      name: "The Ring",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/The_Ring",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Ring of Miquella",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ring_of_Miquella",
      dlc: true,
    },
    {
      type: "gestures",
      name: "Erudition",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Erudition",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Prayer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Prayer",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Desperate Prayer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Desperate_Prayer",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Rapture",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rapture",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Inner Order",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Inner_Order",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Outer Order",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Outer_Order",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Golden Order Totality",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden_Order_Totality",
      dlc: false,
    },
    {
      type: "gestures",
      name: "The Two Fingers",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/The_Two_Fingers",
      dlc: true,
    },
    {
      type: "gestures",
      name: "Extreme Repentance",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Extreme_Repentance",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Grovel for Mercy",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grovel_for_Mercy",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Crossed Legs",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crossed_Legs",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Dozing Cross-Legged",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dozing_Cross-Legged",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Rest",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rest",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Sitting Sideways",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sitting_Sideways",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Dejection",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dejection",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Patches' Crouch",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Patches'_Crouch",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Balled Up",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Balled_Up",
      dlc: false,
    },
    {
      type: "gestures",
      name: "Spread Out",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spread_Out",
      dlc: false,
    },
  ],
};
