import { MeleWeaponsSubCategoryMap } from "../../../global-types";

export const meleWeaponsData: MeleWeaponsSubCategoryMap = {
  daggers: [
    {
      type: "meleWeapons",
      name: "Dagger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dagger",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Parrying Dagger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Parrying+Dagger",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Misericorde",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Misericorde",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Great Knife",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great+Knife",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bloodstained Dagger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodstained+Dagger",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Erdsteel Dagger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Erdsteel+Dagger",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Fire Knight's Shortsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fire+Knight's+Shortsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Wakizashi",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wakizashi",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Main-gauche",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Main-gauche",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Celebrant's Sickle",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Celebrant's+Sickle",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ivory Sickle",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ivory+Sickle",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Crystal Knife",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crystal+Knife",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Scorpion's Stinger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scorpion's+Stinger",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Cinquedea",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cinquedea",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Glintstone Kris",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Glintstone+Kris",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Reduvia",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Reduvia",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Blade of Calling",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blade+of+Calling",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Black Knife",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black+Knife",
      legendary: false,
      dlc: false,
    },
  ],
  throwingBlades: [
    {
      type: "meleWeapons",
      name: "Smithscript Dagger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithscript+Dagger",
      legendary: false,
      dlc: false,
    },
  ],
  straightSwords: [
    {
      type: "meleWeapons",
      name: "Short Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Short+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Longsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Longsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Broadsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Broadsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Weathered Straight Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Weathered+Straight+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Lordsworn's Straight Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lordsworn's+Straight+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Noble's Slender Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Noble's+Slender+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Cane Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cane+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Stone-Sheathed Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stone-Sheathed+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Warhawk's Talon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Warhawk's+Talon",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Lazuli Glintstone Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lazuli+Glintstone+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Carian Knight's Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Carian+Knight's+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Crystal Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crystal+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rotten Crystal Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rotten+Crystal+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Miquellan Knight's Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Miquellan+Knight's+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ornamental Straight Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ornamental+Straight+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Golden Epitaph",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Epitaph",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sword of St Trina",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sword+of+St+Trina",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Velvet Sword of St Trina",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Velvet+Sword+of+St+Trina",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Regalia of Eochaid",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Regalia+of+Eochaid",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Coded Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Coded+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sword of Night and Flame",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sword+of+Night+and+Flame",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sword of Darkness",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sword+of+Darkness",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sword of Light",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sword+of+Light",
      legendary: false,
      dlc: false,
    },
  ],

  lightGreatswords: [
    {
      type: "meleWeapons",
      name: "Milady",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Milady",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Leda's Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Leda's+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rellana's Twinblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rellana's+Twinblade",
      legendary: false,
      dlc: false,
    },
  ],
  greatswords: [
    {
      type: "meleWeapons",
      name: "Bastard Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bastard+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Claymore",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Claymore",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Iron Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Iron+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Lordsworn's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lordsworn's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Knight's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Knight's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Banished Knight's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Banished+Knight's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Lizard Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lizard+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Forked Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Forked+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Flamberge",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flamberge",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gargoyle's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gargoyle's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gargoyle's Blackblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gargoyle's+Blackblade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Inseperable Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Inseperable+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sword of Milos",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sword+of+Milos",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Marais Excutioner's Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Marais+Excutioner's+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Greatsword of Solitude",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greatsword+of+Solitude",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ordovis's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ordovis's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Alabaster Lord's Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Alabaster+Lord's+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Death's Poker",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Death's+Poker",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Helphen's Steeple",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Helphen's+Steeple",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Blasphemous Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blasphemous+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Golden Order Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Order+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Dark Moon Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dark+Moon+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Greatsword of Damnation",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greatsword+of+Damnation",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sacred Relic Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sacred+Relic+Sword",
      legendary: false,
      dlc: false,
    },
  ],
  colossalSwords: [
    {
      type: "meleWeapons",
      name: "Zweihander",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Zweihander",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Watchdog's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Watchdog's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Fire Knight's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fire+Knight's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Troll's Golden Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Troll's+Golden+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Troll Knight's Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Troll+Knight's+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Moonrithyll's Knight Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Moonrithyll's+Knight+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Royal Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Royal+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Grafted Blade Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grafted+Blade+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ruins Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ruins+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ancient Meteoric Ore Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ancient+Metoric+Ore+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Starscourge Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Starscourge+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Greatsword of Radahn (Lord)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greatsword+of+Radahn+(Lord)",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Greatsword of Radahn (Light)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greatsword+of+Radahn+(Light)",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Godslayer's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Godslayer's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Maliketh's Black Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Maliketh's+Black+Blade",
      legendary: false,
      dlc: false,
    },
  ],
  thrustingSwords: [
    {
      type: "meleWeapons",
      name: "Rapier",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rapier",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Estoc",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Estoc",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Noble's Estoc",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Noble's+Estoc",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Cleanrot Knight's Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cleanrot+Knight's+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rogier's Rapier",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rogier's+Rapier",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Antspur Rapier",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Antspur+Rapier",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Frozen Needle",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Frozen+Needle",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Carian Sorcery Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Carian+Sorcery+Sword",
      legendary: false,
      dlc: false,
    },
  ],
  heavyThrustingSwords: [
    {
      type: "meleWeapons",
      name: "Great Epee",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great+Epee",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Queelign's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Queelign's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Godskin Stitcher",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Godskin+Stitcher",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bloody Helice",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloody+Helice",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Dragon King's Cragblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragon+King's+Cragblade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sword Lance",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sword+Lance",
      legendary: false,
      dlc: false,
    },
  ],
  curvedSwords: [
    {
      type: "meleWeapons",
      name: "Scimitar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scimitar",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Falchion",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Falchion",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Shamshir",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shamshir",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Grossmesser",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grossmesser",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bandit's Curved Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bandit's+Curved+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Shotel",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shotel",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Scavenger's Curved Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scavenger's+Curved+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Mantis Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Mantis+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Beastman's Curved Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Beastman's+Curved+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Flowing Curved Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flowing+Curved+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Serpent-God's Curved Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Serpent-God's+Curved+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Magma Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Magma+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Spirit Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spirit+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Nox Flowing Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Nox+Flowing+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Wing of Ashel",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wing+of+Ashel",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Falx",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Falx",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Dancing Blade of Ranah",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dancing+Blade+of+Ranah",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Horned Warrior's Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Horned+Warrior's+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Eclipse Shotel",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Eclipse+Shotel",
      legendary: false,
      dlc: false,
    },
  ],
  curvedGreatswords: [
    {
      type: "meleWeapons",
      name: "Dismounter",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dismounter",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Omen Cleaver",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Omen+Cleaver",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Monk's Flameblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Monk's+Flameblade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Beastman's Cleaver",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Beastman's+Cleaver",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Freyja's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Freyja's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bloodhound's Fang",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodhound's+Fang",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Onyx Lord's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Onyx+Lord's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Zamor Curved Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Zamor+Curved+Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Magma Wyrm's Scalesword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Magma+Wyrm's+Scalesword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Horned Warrior's Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Horned+Warrior's+Greatsword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Morgott's Cursed Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Morgott's+Cursed+Sword",
      legendary: false,
      dlc: false,
    },
  ],
  backhandBlades: [
    {
      type: "meleWeapons",
      name: "Backhand Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Backhand+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Smithscript Cirque",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithscript+Cirque",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Curseblade's Cirque",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Curseblade's+Cirque",
      legendary: false,
      dlc: false,
    },
  ],
  katanas: [
    {
      type: "meleWeapons",
      name: "Uchigatana",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Uchigatana",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Nagakiba",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Nagakiba",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Serpentbone Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Serpentbone+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Meteoric Ore Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Meteoric_Ore_Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Moonveil",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Moonveil",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sword of Night",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sword_of_Night",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rivers of Blood",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rivers_of_Blood",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Dragonscale Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragonscale_Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Star-Lined Sword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Star-Lined_Sword",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Hand of Malenia",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hand_of_Malenia",
      legendary: false,
      dlc: false,
    },
  ],
  greatKatanas: [
    {
      type: "meleWeapons",
      name: "Great Katana",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great_Katana",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Dragon Hunter's Great Katana",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragon_Hunter's_Great_Katana",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rakshasa's Great Katana",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rakshasa's_Great_Katana",
      legendary: false,
      dlc: false,
    },
  ],
  twinblades: [
    {
      type: "meleWeapons",
      name: "Twinblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Twinblade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Twinned Knight Swords",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Twinned_Knight_Swords",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Black Steel Twinblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black_Steel_Twinblade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Godskin Peeler",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Godskin_Peeler",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gargoyle's Twinblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gargoyle's_Twinblade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gargoyle's Black Blades",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gargoyle's_Black_Blades",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Eleonora's Poleblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Eleonora's_Poleblade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Euporia",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Euporia",
      legendary: false,
      dlc: false,
    },
  ],
  axes: [
    {
      type: "meleWeapons",
      name: "Hand Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hand_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Forked Hatchet",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Forked_Hatchet",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Forked-Tongue Hatchet",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Forked-Tongue_Hatchet",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Battle Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Battle_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Mesmmer Soldier's Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Mesmmer_Soldier's_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Warped Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Warped_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Jawbone Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Jawbone_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Iron Cleaver",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Iron_Cleaver",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Highland Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Highland_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Smithscript Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithscript_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Celebrant's Cleaver",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Celebrant's_Cleaver",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Sacrificial Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sacrificial_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Icerind Hatchet",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Icerind_Hatchet",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ripple Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ripple_Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Stormhawk Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stormhawk_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rosus Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rosus_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Death Knight's Twin Axes",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Death_Knight's_Twin_Axes",
      legendary: false,
      dlc: false,
    },
  ],
  greatAxes: [
    {
      type: "meleWeapons",
      name: "Greataxe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greataxe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Crescent Moon Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crescent_Moon_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Longhaft Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Longhaft_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Executioner's Greataxe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Executioner's_Greataxe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Great Omenkiller Cleaver",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great_Omenkiller_Cleaver",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rusted Anchor",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rusted_Anchor",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Butchering Knife",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Butchering_Knife",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bonny Butchering Knife",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bonny_Butchering_Knife",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gargoyle's Great Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gargoyle's_Great_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gargoyle's Black Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gargoyle's_Black_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Death Knight's Longhaft Axe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Death_Knight's_Longhaft_Axe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Winged Greathorn",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Winged_Greathorn",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Axe of Godrick",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Axe_of_Godrick",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Putrescence Cleaver",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Putrescence_Cleaver",
      legendary: false,
      dlc: false,
    },
  ],
  hammers: [
    {
      type: "meleWeapons",
      name: "Club",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Club",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Curved Club",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Curved_Club",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Spiked Club",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spiked_Club",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Stone Club",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stone_Club",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Mace",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Mace",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Morning Star",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Morning_Star",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Warpick",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Warpick",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Monk's Flamemace",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Monk's_Flamemace",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Varre's Bouquet",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Varre's_Bouquet",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Envoy's Horn",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Envoy's_Horn",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Nox Flowing Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Nox_Flowing_Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ringed Finger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ringed_Finger",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Scepter of the All-Knowing",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scepter_of_the_All-Knowing",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Flowerstone Gavel",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flowerstone_Gavel",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Marika's Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Marika's_Hammer",
      legendary: false,
      dlc: false,
    },
  ],
  flails: [
    {
      type: "meleWeapons",
      name: "Flail",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flail",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Nightrider Flail",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Nightrider_Flail",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Chainlink Flail",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Chainlink_Flail",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Family Heads",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Family_Heads",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Serpent Flail",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Serpent_Flail",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bastard's Stars",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bastard's_Stars",
      legendary: false,
      dlc: false,
    },
  ],
  greatHammers: [
    {
      type: "meleWeapons",
      name: "Large Club",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Large_Club",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Curved Great Club",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Curved_Great_Club",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Great Mace",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great_Mace",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Pickaxe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Pickaxe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Brick Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Brick_Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Battle Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Battle_Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rotten Battle Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rotten_Battle_Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Celebrant's Skull",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Celebrant's_Skull",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Great Stars",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great_Stars",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Black Steel Greathammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black_Steel_Greathammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Smithscript Greathammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithscript_Greathammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Greathorn Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greathorn_Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Envoy's Long Horn",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Envoy's_Long_Horn",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Cranial Vessel Candlestand",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cranial_Vessel_Candlestand",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Beastclaw Greathammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Beastclaw_Greathammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Devourer's Scepter",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Devourer's_Scepter",
      legendary: false,
      dlc: false,
    },
  ],
  colossalWeapons: [
    {
      type: "meleWeapons",
      name: "Duelist Greataxe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Duelist_Greataxe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rotten Greataxe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rotten_Greataxe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Golem's Halberd",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golem's_Halberd",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Giant-Crusher",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Giant-Crusher",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Prelate's Inferno Crozier",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Prelate's_Inferno_Crozier",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Great Club",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great_Club",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Troll's Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Troll's_Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Dragon Greatclaw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragon_Greatclaw",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bloodfiend's Arm",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodfiend's_Arm",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Watchdog's Staff",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Watchdog's_Staff",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Staff of the Avatar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Staff_of_the_Avatar",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rotten Staff",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rotten_Staff",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Envoy's Greathorn",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Envoy's_Greathorn",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ghiza's Wheel",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghiza's_Wheel",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Fallingstar Beast Jaw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fallingstar_Beast_Jaw",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Anvil Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Anvil_Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Devonia's Hammer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Devonia's_Hammer",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Axe of Godfrey",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Axe_of_Godfrey",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Shadow Sunflower Blossom",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shadow_Sunflower_Blossom",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gazing Finger",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gazing_Finger",
      legendary: false,
      dlc: false,
    },
  ],
  spears: [
    {
      type: "meleWeapons",
      name: "Short Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Short_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Iron Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Iron_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Partisan",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Partisan",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Pike",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Pike",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Swift Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Swift_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Spiked Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spiked_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Cross-Naginata",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cross-Naginata",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Clayman's Harpoon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Clayman's_Harpoon",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bloodfiend's Fork",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodfiend's_Fork",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Smithscript Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithscript_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Celebrant's Rib-Rake",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Celebrant's_Rib-Rake",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Torchpole",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Torchpole",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Inquisitor's Girandole",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Inquisitor's_Girandole",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Crystal Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crystal_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Rotten Crystal Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rotten_Crystal_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Cleanrot Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cleanrot_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Death Ritual Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Death_Ritual_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bolt of Gransax",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bolt_of_Gransax",
      legendary: false,
      dlc: false,
    },
  ],
  greatSpears: [
    {
      type: "meleWeapons",
      name: "Lance",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lance",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Messmer Soldier's Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Messmer_Soldier's_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Treespear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Treespear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Serpent-Hunter",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Serpent-Hunter",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Siluria's Tree",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Siluria's_Tree",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Vyke's War Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Vyke's_War_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Barbed Staff-Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Barbed_Staff-Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bloodfiend's Sacred Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodfiend's_Sacred_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Mohgwyn's Sacred Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Mohgwyn's_Sacred_Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Spear of the Impaler",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spear_of_the_Impaler",
      legendary: false,
      dlc: false,
    },
  ],
  helberds: [
    {
      type: "meleWeapons",
      name: "Halberd",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Halberd",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Banished Knight's Halberd",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Banished_Knight's_Halberd",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Lucerne",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lucerne",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Glaive",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Glaive",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Vulgar Militia Shotel",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Vulgar_Militia_Shotel",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Vulgar Militia Saw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Vulgar_Militia_Saw",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Guardian's Swordspear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Guardian's_Swordspear",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gargoyle's Halberd",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gargoyle's_Halberd",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Gargoyle's Black Halberd",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gargoyle's_Black_Halberd",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Nightrider Glaive",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Nightrider_Glaive",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Pest's Glaive",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Pest's_Glaive",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Ripple Crescent Halberd",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ripple_Crescent_Halberd",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Golden Halberd",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden_Halberd",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Dragon Halberd",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragon_Halberd",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Loretta's War Sickle",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Loretta's_War_Sickle",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Commander's Standard",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Commander's_Standard",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Spirit Glaive",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spirit_Glaive",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Poleblade of the Bud",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Poleblade_of_the_Bud",
      legendary: false,
      dlc: false,
    },
  ],
  reapers: [
    {
      type: "meleWeapons",
      name: "Scythe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scythe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Grave Scythe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave_Scythe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Halo Scythe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Halo_Scythe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Winged Scythe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Winged_Scythe",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Obsidian Lamina",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Obsidian_Lamina",
      legendary: false,
      dlc: false,
    },
  ],
  whips: [
    {
      type: "meleWeapons",
      name: "Whip",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Whip",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Thorned Whip",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Thorned_Whip",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Urumi",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Urumi",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Hoslow's Petal Whip",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hoslow's_Petal_Whip",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Tooth Whip",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Tooth_Whip",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Magma Whip Candlestick",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Magma_Whip_Candlestick",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Giant's Red Braid",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Giant's_Red_Braid",
      legendary: false,
      dlc: false,
    },
  ],
  fists: [
    {
      type: "meleWeapons",
      name: "Caestus",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Caestus",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Spiked Caestus",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spiked_Caestus",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Katar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Katar",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Pata",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Pata",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Iron Ball",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Iron_Ball",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Star Fist",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Star_Fist",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Clinging Bone",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Clinging_Bone",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Veteran's Prosthesis",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Veteran's_Prosthesis",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Cipher Pata",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cipher_Pata",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Poisoned Hand",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Poisoned_Hand",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Madding Hand",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Madding_Hand",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Golem Fist",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golem_Fist",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Thiollier's Hidden Needle",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Thiollier's_Hidden_Needle",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Grafted Dragon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grafted_Dragon",
      legendary: false,
      dlc: false,
    },
  ],
  handToHand: [
    {
      type: "meleWeapons",
      name: "Dryleaf Arts",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dryleaf_Arts",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Dane's Footwork",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dane's_Footwork",
      legendary: false,
      dlc: false,
    },
  ],
  claws: [
    {
      type: "meleWeapons",
      name: "Hookclaws",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hookclaws",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Bloodhound Claws",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodhound_Claws",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Venomous Fang",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Venomous_Fang",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Raptor Talons",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Raptor_Talons",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Claws of Night",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Claws_of_Night",
      legendary: false,
      dlc: false,
    },
  ],
  beastClaws: [
    {
      type: "meleWeapons",
      name: "Beast Claw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Beast_Claw",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Red Bear's Claw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Red_Bear's_Claw",
      legendary: false,
      dlc: false,
    },
  ],
  perfumeBottles: [
    {
      type: "meleWeapons",
      name: "Firespark",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Firespark",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Lightning",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lightning",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Chilling",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Chilling",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Frenzyflame",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Frenzyflame",
      legendary: false,
      dlc: false,
    },
    {
      type: "meleWeapons",
      name: "Deadly Poison",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Deadly_Poison",
      legendary: false,
      dlc: false,
    },
  ],
};
