import type { AshesOfWarSubCategoryMap } from "../../../global-types";

export const ashesOfWarData: AshesOfWarSubCategoryMap = {
  heavy: [
    {
      type: "ashesOfWar",
      name: "Stamp (Upward Cut)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stamp+Upward+Cut",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Stamp (Sweep)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stamp+Sweep",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Wild Strikes",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wild+Strikes",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Lion's Claw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lion's+Claw",
      dlc: false,
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/ash_of_war_lions_claw_elden_ring_wiki_guide_200px.png",
    },
    {
      type: "ashesOfWar",
      name: "Savage Lion's Claw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Savage+Lion's+Claw",
      dlc: false,
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/ash_of_war_savage_lions_claw_ashes_of_war_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png",
    },
    {
      type: "ashesOfWar",
      name: "Cragblade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cragblade",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Kick",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Kick",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Endure",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Endure",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Ground Slam",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ground+Slam",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Earthshaker",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Earthshaker",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Hoarah Loux's Earthshaker",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hoarah+Loux's+Earthshaker",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "War Cry",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/War+Cry",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Barbaric Roar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Barbaric+Roar",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Braggart's Roar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Braggart's+Roar",
      dlc: false,
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/ash_of_war_braggart's_roar_elden_ring_wiki_guide_200px.png",
    },
    {
      type: "ashesOfWar",
      name: "Troll's Roar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Troll's+Roar",
      dlc: false,
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/ash_of_war_troll's_roar_elden_ring_wiki_guide_200px.png",
    },
  ],
  keen: [
    {
      type: "ashesOfWar",
      name: "Spinning Slash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spinning+Slash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Impaling Thrust",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Impaling+Thrust",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Blind Spot",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blind+Spot",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Swift Slash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Swift+Slash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Piercing Fang",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Piercing+Fang",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Repeating Thrust",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Repeating+Thrust",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Double Slash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Double+Slash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Sword Dance",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sword+Dance",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Unsheathe",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Unsheathe",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Overhead Stance",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Overhead+Stance",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Quickstep",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Quickstep",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Bloodhound Step",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodhound+Step",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Raptor of the Mists",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Raptor+of+the+Mists",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Beast's Roar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Beast's+Roar",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Savage Claws",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Savage+Claws",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Raging Beast",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Raging+Beast",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Piercing Throw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Piercing+Throw",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Scattershot Throw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scattershot+Throw",
      dlc: false,
    },
  ],
  quality: [
    {
      type: "ashesOfWar",
      name: "Square Off",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Square+Off",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Wing Stance",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wing+Stance",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Charge Forth",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Charge+Forth",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Giant Hunt",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Giant+Hunt",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Storm Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Storm+Blade",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Storm Assault",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Storm+Assault",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Stormcaller",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stormcaller",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Storm Stomp",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Storm+Stomp",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Vacuum Slice",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Vacuum+Slice",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Phantom Slash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Phantom+Slash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Determination",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Determination",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Royal Knight's Resolve",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Royal+Knight's+Resolve",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Spinning Strikes",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spinning+Strikes",
      dlc: false,
    },
  ],
  magic: [
    {
      type: "ashesOfWar",
      name: "Glintstone Pebble",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Glintstone+Pebble",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Glintblade Phalanx",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Glintblade+Phalanx",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Carian Greatsword",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Carian+Greatsword",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Carian Grandeur",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Carian+Grandeur",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Carian Sovereignty",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Carian+Sovereignty",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Spinning Weapon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spinning+Weapon",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Loretta's Slash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Loretta's+Slash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Gravitas",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gravitas",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Spinning Gravity Thrust",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spinning+Gravity+Thrust",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Waves of Darkness",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Waves+of+Darkness",
      dlc: false,
    },
  ],
  flameLightning: [
    {
      type: "ashesOfWar",
      name: "Flaming Strike",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flaming+Strike",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Flame of the Redmanes",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame+of+the+Redmanes",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Eruption",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Eruption",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Prelate's Charge",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Prelate's+Charge",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Black Flame Tornado",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black+Flame+Tornado",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Flame Skewer",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame+Skewer",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Flame Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame+Spear",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Thunderbolt",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Thunderbolt",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Lightning Slash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lightning+Slash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Blinkbolt",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blinkbolt",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Lightning Ram",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lightning+Ram",
      dlc: false,
    },
  ],
  sacred: [
    {
      type: "ashesOfWar",
      name: "Sacred Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sacred+Blade",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Prayerful Strike",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Prayerful+Strike",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Sacred Ring of Light",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sacred+Ring+of+Light",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Sacred Order",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sacred+Order",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Shared Order",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shared+Order",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Golden Land",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Land",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Golden Slam",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Slam",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Golden Vow",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Vow",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Vow of the Indomitable",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Vow+of+the+Indomitable",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Holy Ground",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Holy+Ground",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Aspects of the Crucible: Wings",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Aspects+of+the+Crucible:+Wings",
      dlc: false,
    },
  ],
  poisonBloodCold: [
    {
      type: "ashesOfWar",
      name: "Poisonous Mist",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Poisonous+Mist",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Poison Moth Flight",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Poison+Moth+Flight",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "The Poison Flower Blooms Twice",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/The+Poison+Flower+Blooms+Twice",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Blood Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blood+Blade",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Bloody Slash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloody+Slash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Blood Tax",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blood+Tax",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Seppuku",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Seppuku",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Ice Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ice+Spear",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Chilling Mist",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Chilling+Mist",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Ghostflame Call",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghostflame+Call",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Hoarfrost Stomp",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hoarfrost+Stomp",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Divine Beast Frost Stomp",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Divine+Beast+Frost+Stomp",
      dlc: false,
    },
  ],
  occult: [
    {
      type: "ashesOfWar",
      name: "Spectral Lance",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spectral+Lance",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Lifesteal Fist",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lifesteal+Fist",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "White Shadow's Lure",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/White+Shadow's+Lure",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Assassin's Gambit",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Assassin's+Gambit",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Shriek of Sorrow",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shriek+of+Sorrow",
      dlc: false,
    },
  ],
  noAffinityHandToHandAndPerfume: [
    {
      type: "ashesOfWar",
      name: "Palm Blast",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Palm+Blast",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Dryleaf Whirlwind",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dryleaf+Whirlwind",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Wall of Sparks",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wall+of+Sparks",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Rolling Sparks",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rolling+Sparks",
      dlc: false,
    },
  ],
  noAffinityRanged: [
    {
      type: "ashesOfWar",
      name: "Mighty Shot",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Mighty+Shot",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Through and Through",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Through+and+Through",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Igon's Drake Hunt",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Igon's+Drake+Hunt",
      dlc: false,
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/ash_of_war_igons_drake_hunt_ashes_of_war_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png",
    },
    {
      type: "ashesOfWar",
      name: "Barrage",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Barrage",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Sky Shot",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sky+Shot",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Enchanted Shot",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Enchanted+Shot",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Rain of Arrows",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rain+of+Arrows",
      dlc: false,
    },
  ],
  noAffinityShield: [
    {
      type: "ashesOfWar",
      name: "Parry",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Parry",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Golden Parry",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Parry",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Storm Wall",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Storm+Wall",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Shield Bash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shield+Bash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Shield Crash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shield+Crash",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Barricade Shield",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Barricade+Shield",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Thops's Barrier",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Thops's+Barrier",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Carian Retaliation",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Carian+Retaliation",
      dlc: false,
    },
    {
      type: "ashesOfWar",
      name: "Shield Strike",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shield+Strike",
      dlc: false,
      imgUrl:
        "https://eldenring.wiki.fextralife.com/file/Elden-Ring/ash_of_war_shield_strike_3_ashes_of_war_elden_ring_shadow_of_the_erdtree_dlc_wiki_guide_200px.png",
    },
    {
      type: "ashesOfWar",
      name: "No Skill",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/No+Skill",
      dlc: false,
    },
  ],
};
