import { IncantationsSubCategoryMap } from "../../../global-types";

export const incantationsData: IncantationsSubCategoryMap = {
  twoFingers: [
    {
      type: "incantations",
      name: "Urgent Heal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Urgent+Heal",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Heal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Heal",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Great Heal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great+Heal",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Lord's Heal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lord's+Heal",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Cure Poison",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cure+Poison",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Lord's Aid",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lord's+Aid",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Magic Fortification",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Magic+Fortification",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Flame Fortification",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame+Fortification",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Lightning Fortification",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lightning+Fortification",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Divine Fortification",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Divine+Fortification",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Lord's Divine Fortification",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lord's+Divine+Fortification",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Rejection",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rejection",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Shadow Bait",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Shadow+Bait",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Darkness",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Darkness",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Assassin's Approach",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Assassin's+Approach",
      legendary: false,
      dlc: false,
    },
  ],
  "erdtree&GoldenOrder": [
    {
      type: "incantations",
      name: "Golden Vow",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Vow",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Barrier of Gold",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Barrier+of+Gold",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Golden Lightning Fortification",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Lightning+Fortification",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Protection of the Erdtree",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Protection+of+the+Erdtree",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Wrath of Gold",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wrath+of+Gold",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Wrath from Far",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Wrath+from+Far",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Heal from Afar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Heal+from+Afar",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Erdtree Heal",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Erdtree+Heal",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Blessing's Boon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blessing's+Boon",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Blessing of the Erdtree",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Blessing+of+the+Erdtree",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Minor Erdtree",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Minor+Erdtree",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Aspects of the Crucible: Breath",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Aspects+of+the+Crucible:+Breath",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Aspects of the Crucible: Horns",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Aspects+of+the+Crucible:+Horns",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Aspects of the Crucible: Tail",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Aspects+of+the+Crucible:+Tail",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Aspects of the Crucible: Thorns",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Aspects+of+the+Crucible:+Thorns",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Aspects of the Crucible: Bloom",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Aspects+of+the+Crucible:+Bloom",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Land of Shadow",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Land+of+Shadow",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Elden Stars",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Elden+Stars",
      legendary: true,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Black Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Discus of Light",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Discus+of+Light",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Triple Rings of Light",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Triple+Rings+of+Light",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Radagon's Rings of Light",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Radagon's+Rings+of+Light",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Multilayered Ring of Light",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Multilayered+Ring+of+Light",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Litany of Proper Death",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Litany+of+Proper+Death",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Order Healing",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Order+Healing",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Order's Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Order's+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Immutable Shield",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Immutable+Shield",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Law of Causality",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Law+of+Causality",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Law of Regression",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Law+of+Regression",
      legendary: false,
      dlc: false,
    },
  ],
  miquella: [
    {
      type: "incantations",
      name: "Light of Miquella",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Light+of+Miquella",
      legendary: false,
      dlc: true,
    },
  ],
  dragonCult: [
    {
      type: "incantations",
      name: "Lightning Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lightning+Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Knight's Lightning Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Knight's+Lightning+Spear",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Lightning Strike",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lightning+Strike",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Honed Bolt",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Honed+Bolt",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Ancient Dragon's Lightning Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ancient+Dragon's+Lightning+Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Ancient Dragon's Lightning Strike",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ancient+Dragon's+Lightning+Strike",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Lansseax's Glaive",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lansseax's+Glaive",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Fortissax's Lightning Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fortissax's+Lightning+Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Frozen Lightning Spear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Frozen+Lightning+Spear",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Death Lightning",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Death+Lightning",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Electrify Armament",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Electrify+Armament",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Electrocharge",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Electrocharge",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Dragonbolt Blessing",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragonbolt+Blessing",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Vyke's Dragonbolt",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Vyke's+Dragonbolt",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Dragonbolt of Florissax",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragonbolt+of+Florissax",
      legendary: false,
      dlc: true,
    },
  ],
  shadowRealm: [
    {
      type: "incantations",
      name: "Golden Arcs",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Arcs",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Giant Golden Arc",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Giant+Golden+Arc",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Spira",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spira",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Watchful Spirit",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Watchful+Spirit",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Divine Bird Feathers",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Divine+Bird+Feathers",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Divine Beast Tornado",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Divine+Beast+Tornado",
      legendary: false,
      dlc: true,
    },
  ],
  "fireMonk&FireGiant": [
    {
      type: "incantations",
      name: "Catch Flame",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Catch+Flame",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "O, Flame!",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/O,+Flame!",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Flame Sling",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame+Sling",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Giantsflame Take Thee",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Giantsflame+Take+Thee",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Flame, Fall Upon Them",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame,+Fall+Upon+Them",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Flame of the Fell God",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame+of+the+Fell+God",
      legendary: true,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Surge, O Flame!",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Surge,+O+Flame!",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Whirl, O Flame!",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Whirl,+O+Flame!",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Burn, O Flame!",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Burn,+O+Flame!",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Flame, Cleanse Me",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame,+Cleanse+Me",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Flame, Protect Me",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame,+Protect+Me",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Flame, Grant Me Strength",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame,+Grant+Me+Strength",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Fire's Deadly Sin",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fire's+Deadly+Sin",
      legendary: false,
      dlc: false,
    },
  ],
  messmer: [
    {
      type: "incantations",
      name: "Fire Serpent",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Fire+Serpent",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Rain of Fire",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rain+of+Fire",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Messmer's Orb",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Messmer's+Orb",
      legendary: false,
      dlc: true,
    },
  ],
  "godskin&Gurranq": [
    {
      type: "incantations",
      name: "Black Flame",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black+Flame",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Scouring Black Flame",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scouring+Black+Flame",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Black Flame Ritual",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black+Flame+Ritual",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Black Flame Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black+Flame+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Black Flame's Protection",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Black+Flame's+Protection",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Noble Presence",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Noble+Presence",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Beast Claw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Beast+Claw",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Gurranq's Beast Claw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Gurranq's+Beast+Claw",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Bestial Sling",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bestial+Sling",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Stone of Gurranq",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stone+of+Gurranq",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Bestial Constitution",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bestial+Constitution",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Bestial Vitality",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bestial+Vitality",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Roar of Rugalea",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Roar+of+Rugalea",
      legendary: false,
      dlc: true,
    },
  ],
  "blood&Rot": [
    {
      type: "incantations",
      name: "Swarm of Flies",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Swarm+of+Flies",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Rotten Butterflies",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rotten+Butterflies",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Bloodflame Talons",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodflame+Talons",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Furious Blade of Ansbach",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Furious+Blade+of+Ansbach",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Bloodboon",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodboon",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Bloodflame Blade",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodflame+Blade",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Poison Mist",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Poison+Mist",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Poison Armament",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Poison+Armament",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Pest Threads",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Pest+Threads",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Pest-Thread Spears",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Pest-Thread+Spears",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Scarlet Aeonia",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scarlet+Aeonia",
      legendary: false,
      dlc: false,
    },
  ],
  threeFingers: [
    {
      type: "incantations",
      name: "The Flame of Frenzy",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/The+Flame+of+Frenzy",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Midra's Flame of Frenzy",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Midra's+Flame+of+Frenzy",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Unendurable Frenzy",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Unendurable+Frenzy",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Frenzied Burst",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Frenzied+Burst",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Howl of Shabriri",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Howl+of+Shabriri",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Inescapable Frenzy",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Inescapable+Frenzy",
      legendary: false,
      dlc: false,
    },
  ],
  dragonCommunion: [
    {
      type: "incantations",
      name: "Dragonfire",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragonfire",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Agheel's Flame",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Agheel's+Flame",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Magma Breath",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Magma+Breath",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Theodorix's Magma",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Theodorix's+Magma",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Glintstone Breath",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Glintstone+Breath",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Smarag's Glintstone Breath",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smarag's+Glintstone+Breath",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Rotten Breath",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Rotten+Breath",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Ekzykes's Decay",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ekzykes's+Decay",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Dragonice",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragonice",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Borealis's Mist",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Borealis's+Mist",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Ghostflame Breath",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghostflame+Breath",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Placidusax's Ruin",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Placidusax's+Ruin",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Dragonclaw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragonclaw",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Dragonmaw",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dragonmaw",
      legendary: false,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Greyoll's Roar",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greyoll's+Roar",
      legendary: true,
      dlc: false,
    },
    {
      type: "incantations",
      name: "Bayle's Flame Lightning",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bayle's+Flame+Lightning",
      legendary: false,
      dlc: true,
    },
    {
      type: "incantations",
      name: "Bayle's Tyranny",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bayle's+Tyranny",
      legendary: false,
      dlc: true,
    },
  ],
};
