import { TearsOrUpgradesCategoryMap } from "../../../global-types";

export const tearsAndUpgradesData: TearsOrUpgradesCategoryMap = {
  crystalTears: [
    {
      type: "tearsAndUpgrades",
      name: "Crimson Crystal Tear (Left)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimson+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Crimson Crystal Tear (Right)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimson+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Crimsonspill Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimsonspill+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Crimsonburst Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimsonburst+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Crimsonburst Dried Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimsonburst+Dried+Tear",
      dlc: true,
    },
    {
      type: "tearsAndUpgrades",
      name: "Cerulean Crystal Tear (Left)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cerulean+Crystal+Tear+(Left)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Cerulean Crystal Tear (Right)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cerulean+Crystal+Tear+(Right)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Greenspill Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greenspill+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Greenburst Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Greenburst+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Strength-Knot Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Strength-Knot+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Dexterity-Knot Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Dexterity-Knot+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Intelligence-Knot Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Intelligence-Knot+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Faith-Knot Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Faith-Knot+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Opaline Hardtear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Opaline+Hardtear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Speckled Hardtear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Speckled+Hardtear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Leaden Hardtear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Leaden+Hardtear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Deflecting Hardtear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Deflecting+Hardtear",
      dlc: true,
    },
    {
      type: "tearsAndUpgrades",
      name: "Magic-Shrouding Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Magic-Shrouding+Cracked+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Flame-Shrouding Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Flame-Shrouding+Cracked+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Lightning-Shrouding Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Lightning-Shrouding+Cracked+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Holy-Shrouding Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Holy-Shrouding+Cracked+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Stonebarb Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Stonebarb+Cracked+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Spiked Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Spiked+Cracked+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Thorny Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Thorny+Cracked+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Crimson-Sapping Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimson-Sapping+Cracked+Tear",
      dlc: true,
    },
    {
      type: "tearsAndUpgrades",
      name: "Cerulean-Sapping Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cerulean-Sapping+Cracked+Tear",
      dlc: true,
    },
    {
      type: "tearsAndUpgrades",
      name: "Bloodsucking Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Bloodsucking+Cracked+Tear",
      dlc: true,
    },
    {
      type: "tearsAndUpgrades",
      name: "Twiggy Cracked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Twiggy+Cracked+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Winged Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Winged+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Windy Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Windy+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Glovewort Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Glovewort+Crystal+Tear",
      dlc: true,
    },
    {
      type: "tearsAndUpgrades",
      name: "Crimson Bubbletear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimson+Bubbletear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Crimsonwhorl Bubbletear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Crimsonwhorl+Bubbletear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Opaline Bubbletear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Opaline+Bubbletear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Cerulean Hidden Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cerulean+Hidden+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Viridian Hidden Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Viridian+Hidden+Tear",
      dlc: true,
    },
    {
      type: "tearsAndUpgrades",
      name: "Purifying Crystal Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Purifying+Crystal+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ruptured Crystal Tear (Left)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ruptured+Crystal+Tear+(Left)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ruptured Crystal Tear (Right)",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ruptured+Crystal+Tear+(Right)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Oil-Soaked Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Oil-Soaked+Tear",
      dlc: true,
    },
  ],
  upgrades: [
    {
      type: "tearsAndUpgrades",
      name: "Golden Seed",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Golden+Seed",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Sacred Tear",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Sacred+Tear",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Scadutree Fragment",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Scadutree+Fragment",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Revered Spirit Ash",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Revered+Spirit+Ash",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Cracked Pot",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Cracked+Pot",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ritual Pot",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ritual+Pot",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Hefty Cracked Pot",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Hefty+Cracked+Pot",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Perfume Bottle",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Perfume+Bottle",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Memory Stone",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Memory+Stone",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Talisman Pouch",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Talisman+Pouch",
      dlc: false,
    },
  ],
  smithingStones: [
    {
      type: "tearsAndUpgrades",
      name: "Smithing Stone [1]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Stone+(1)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Smithing Stone [2]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Stone+(2)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Smithing Stone [3]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Stone+(3)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Smithing Stone [4]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Stone+(4)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Smithing Stone [5]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Stone+(5)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Smithing Stone [6]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Stone+(6)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Smithing Stone [7]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Stone+(7)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Smithing Stone [8]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Smithing+Stone+(8)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ancient Dragon Smithing Stone",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ancient+Dragon+Smithing+Stone",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [1]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(1)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [2]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(2)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [3]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(3)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [4]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(4)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [5]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(5)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [6]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(6)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [7]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(7)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [8]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(8)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Smithing Stone [9]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Smithing+Stone+(9)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Somber Ancient Dragon Smithing Stone",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Somber+Ancient+Dragon+Smithing+Stone",
      dlc: false,
    },
  ],
  gloveworts: [
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [1]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(1)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [2]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(2)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [3]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(3)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [4]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(4)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [5]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(5)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [6]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(6)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [7]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(7)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [8]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(8)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Grave Glovewort [9]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Grave+Glovewort+(9)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Great Grave Glovewort",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great+Grave+Glovewort",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [1]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(1)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [2]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(2)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [3]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(3)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [4]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(4)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [5]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(5)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [6]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(6)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [7]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(7)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [8]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(8)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Ghost Glovewort [9]",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Ghost+Glovewort+(9)",
      dlc: false,
    },
    {
      type: "tearsAndUpgrades",
      name: "Great Ghost Glovewort",
      collected: false,
      link: "https://eldenring.wiki.fextralife.com/Great+Ghost+Glovewort",
      dlc: false,
    },
  ],
};
